name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Set minimum iOS version to 13.0
        run: |
          sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile || echo "platform :ios, '13.0'" >> ios/Podfile

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios

      - name: Build iOS app (release, no codesign)
        run: flutter build ios --release --no-codesign

      - name: Prepare Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move .app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Create .ipa file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload .ipa to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
